<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE Page [
<!ELEMENT Page (Block)*>
<!ELEMENT Block (Attributes, Text)>
<!ATTLIST Block
  left   CDATA   #REQUIRED
  top    CDATA   #REQUIRED
  right  CDATA   #REQUIRED
  bottom CDATA   #REQUIRED
  depth  CDATA   #REQUIRED
>
<!ELEMENT Attributes (Attribute)*>
<!ELEMENT Attribute EMPTY>
<!ATTLIST Attribute
  name   NMTOKEN #REQUIRED
  value  CDATA   #REQUIRED
>
<!ELEMENT Text (#PCDATA)>
]>

<Page>

  <Block left="62" top="141" right="103" bottom="165" depth="22">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="6" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#546368" />
    </Attributes>
    <Text>Help </Text>
  </Block>
  <Block left="103" top="141" right="169" bottom="165" depth="22">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="6" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#546368" />
    </Attributes>
    <Text>Guidelines </Text>
  </Block>
  <Block left="169" top="141" right="235" bottom="165" depth="22">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="6" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#546368" />
    </Attributes>
    <Text>Subscribe by email </Text>
  </Block>
  <Block left="59" top="188" right="239" bottom="214" depth="8">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="10.8" />
      <Attribute name="realFontWeight" value="700" />
      <Attribute name="realTextColor" value="#346080" />
    </Attributes>
    <Text>Notices</Text>
  </Block>
  <Block left="64" top="224" right="233" bottom="332" depth="10">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#fffaf4" />
      <Attribute name="realFontSize" value="10" />
      <Attribute name="realFontWeight" value="700" />
      <Attribute name="realTextColor" value="#346080" />
    </Attributes>
    <Text>» See our new Second Life Planned Outages Calendar.

» Report bugs in our Issue Tracker.</Text>
  </Block>
  <Block left="59" top="373" right="239" bottom="399" depth="8">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="10.8" />
      <Attribute name="realFontWeight" value="700" />
      <Attribute name="realTextColor" value="#346080" />
    </Attributes>
    <Text>Quality Metrics</Text>
  </Block>
  <Block left="59" top="399" right="249" bottom="1655" depth="10">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="10" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>Curious about Second Life&apos;s stability and performance and what we&apos;re doing to improve it?

See our Second Life Grid Quality Metrics!



 

 
Office Hours

» Meet Lindens in Second Life</Text>
  </Block>
  <Block left="59" top="507" right="226" bottom="543" depth="10">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="10" />
      <Attribute name="realFontWeight" value="700" />
      <Attribute name="realTextColor" value="#4378a4" />
    </Attributes>
    <Text>See our Second Life Grid Quality Metrics!</Text>
  </Block>
  <Block left="59" top="1397" right="239" bottom="1423" depth="8">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="10.8" />
      <Attribute name="realFontWeight" value="700" />
      <Attribute name="realTextColor" value="#346080" />
    </Attributes>
    <Text>Office Hours</Text>
  </Block>
  <Block left="59" top="1619" right="210" bottom="1655" depth="10">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="10" />
      <Attribute name="realFontWeight" value="700" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>» Meet Lindens in Second Life</Text>
  </Block>
  <Block left="747" top="206" right="927" bottom="257" depth="7">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="6" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#546368" />
    </Attributes>
    <Text>Categories
 Select Category -Miscellaneous  (432) Announcements &amp; News  (793) Beta Test Grid  (76) Blog Improvements  (16) Bugs &amp; Fixes  (210) Community  (478) Concierge  (93) Creativity &amp; Ideas  (98) Customer Service  (186) Development  (112) Economy  (45) Education  (7) Events  (35) Forums  (5) Games  (16) Interviews  (7) Land  (55) Marketing  (18) Movies &amp; Machinima  (10) Music  (13) New Releases  (168) Off-Topic  (6) Operations  (79) Other Blogs  (5) Q&amp;A  (12) Quality Assurance  (46) Resident Experience  (242) Scripting  (23) Security  (25) Service Metrics  (8) Service Status  (311) Support Stats  (3) Tips &amp; Tricks  (50) Volunteers  (7) Web Development  (20) Website Status  (63) </Text>
  </Block>
  <Block left="747" top="287" right="927" bottom="338" depth="7">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="6" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#546368" />
    </Attributes>
    <Text>Archives
 Select Month March 2008  (32) February 2008  (86) January 2008  (76) December 2007  (65) November 2007  (85) October 2007  (68) September 2007  (44) August 2007  (59) July 2007  (52) June 2007  (60) May 2007  (49) April 2007  (48) March 2007  (70) February 2007  (55) January 2007  (70) December 2006  (76) November 2006  (68) October 2006  (89) September 2006  (102) August 2006  (66) July 2006  (15) June 2006  (9) May 2006  (16) April 2006  (8) March 2006  (11) February 2006  (8) January 2006  (7) December 2005  (20) November 2005  (12) October 2005  (3) September 2005  (6) August 2005  (9) July 2005  (3) June 2005  (2) May 2005  (4) April 2005  (7) March 2005  (5) February 2005  (1) January 2005  (4) December 2004  (1) November 2004  (6) October 2004  (8) </Text>
  </Block>
  <Block left="747" top="338" right="942" bottom="509" depth="8">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="6" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#546368" />
    </Attributes>
    <Text>

 
A resource offering tools and support for 3D content creation.</Text>
  </Block>
  <Block left="747" top="539" right="927" bottom="565" depth="8">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="10.8" />
      <Attribute name="realFontWeight" value="700" />
      <Attribute name="realTextColor" value="#346080" />
    </Attributes>
    <Text>Meta</Text>
  </Block>
  <Block left="775" top="571" right="927" bottom="583" depth="9">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="6" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#546368" />
    </Attributes>
    <Text>Log in </Text>
  </Block>
  <Block left="775" top="589" right="927" bottom="601" depth="9">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="6" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#546368" />
    </Attributes>
    <Text>Entries RSS </Text>
  </Block>
  <Block left="775" top="607" right="927" bottom="619" depth="9">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="6" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#546368" />
    </Attributes>
    <Text>Comments RSS </Text>
  </Block>
  <Block left="775" top="625" right="927" bottom="637" depth="9">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="6" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#546368" />
    </Attributes>
    <Text>WordPress.com </Text>
  </Block>
  <Block left="268" top="114" right="722" bottom="185" depth="17">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="7.2" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#546368" />
    </Attributes>
    <Text>[RESOLVED] Account Detail Reports Lagging by Roughly Five Hours
Monday, March 10th, 2008 at 10:13 AM by: Teeple Linden </Text>
  </Block>
  <Block left="275" top="208" right="715" bottom="226" depth="19">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="7.2" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#546368" />
    </Attributes>
    <Text>[10:15 a.m. PST –teeple]</Text>
  </Block>
  <Block left="275" top="249" right="715" bottom="285" depth="19">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="7.2" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#546368" />
    </Attributes>
    <Text>Reporting is back in synch with in world transactions now.  Thanks for your patience!</Text>
  </Block>
  <Block left="275" top="310" right="424" bottom="324" depth="20">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="7.2" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#808080" />
    </Attributes>
    <Text>[9:54 a.m. PST –teeple]</Text>
  </Block>
  <Block left="275" top="351" right="716" bottom="383" depth="20">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="7.2" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#808080" />
    </Attributes>
    <Text>The databases have almost finished resynchronizing. Reporting lag is down to about 15 minutes and closing…</Text>
  </Block>
  <Block left="275" top="410" right="319" bottom="424" depth="20">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="7.2" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#808080" />
    </Attributes>
    <Text>***** </Text>
  </Block>
  <Block left="275" top="451" right="711" bottom="519" depth="20">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="7.2" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#808080" />
    </Attributes>
    <Text>[8:08 a.m. PST –teeple] We’ve placed an unusually heavy reporting load on one of our databases this morning, and as a result, resident transactions are taking roughly five hours to become visible on the Website.</Text>
  </Block>
  <Block left="275" top="546" right="706" bottom="596" depth="20">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="7.2" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#808080" />
    </Attributes>
    <Text>The transactions are being captured properly. This is just a synchronization issue between the database instances, and should correct itself later this morning.</Text>
  </Block>
  <Block left="275" top="623" right="504" bottom="637" depth="20">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="7.2" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#808080" />
    </Attributes>
    <Text>We apologize for the inconvenience.</Text>
  </Block>
  <Block left="274" top="682" right="413" bottom="697" depth="29">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="6.75" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#777777" />
    </Attributes>
    <Text>Categories: -Miscellaneous</Text>
  </Block>
  <Block left="685" top="690" right="705" bottom="706" depth="30">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="7.2" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#4378a4" />
    </Attributes>
    <Text>71 </Text>
  </Block>
  <Block left="268" top="758" right="722" bottom="829" depth="17">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="7.2" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#546368" />
    </Attributes>
    <Text>PARCEL MEDIA Video Tutorials: How to play movies, webpages, &amp; more!
Monday, March 10th, 2008 at 9:00 AM by: Torley Linden </Text>
  </Block>
  <Block left="275" top="852" right="715" bottom="906" depth="19">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="7.2" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#546368" />
    </Attributes>
    <Text>I hope you’ve already read Jeska’s post on the new PARCEL MEDIA features in our 1.19.1 Release Candidate viewer! To use ‘em, you’ll need to:</Text>
  </Block>
  <Block left="275" top="1048" right="715" bottom="1084" depth="19">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="7.2" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#546368" />
    </Attributes>
    <Text>I made 3 video tutorials to help you master these new features:
 </Text>
  </Block>
  <Block left="275" top="1107" right="715" bottom="1161" depth="19">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="7.2" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#546368" />
    </Attributes>
    <Text>1. How to play movies, webpages, &amp; more on your land - A friendly intro to existing media options (good if you’ve new to all of this) and I showcase what’s fresh!</Text>
  </Block>
  <Block left="291" top="1554" right="548" bottom="1568" depth="21">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="7.2" />
      <Attribute name="realFontWeight" value="700" />
      <Attribute name="realTextColor" value="#4378a4" />
    </Attributes>
    <Text>DOWNLOAD HIGH-QUALITY VERSION</Text>
  </Block>
  <Block left="275" top="1593" right="453" bottom="1607" depth="20">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="7.2" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#4378a4" />
    </Attributes>
    <Text>Read the rest of this entry »</Text>
  </Block>
  <Block left="274" top="1652" right="656" bottom="1667" depth="29">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="6.75" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#777777" />
    </Attributes>
    <Text>Categories: Community, Creativity &amp; Ideas, Resident Experience, Tips &amp; Tricks</Text>
  </Block>
  <Block left="685" top="1660" right="705" bottom="1676" depth="30">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="7.2" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#4378a4" />
    </Attributes>
    <Text>32 </Text>
  </Block>
  <Block left="268" top="1728" right="722" bottom="1799" depth="17">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="7.2" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#546368" />
    </Attributes>
    <Text>[RESOLVED] A number of regions currently unreachable
Monday, March 10th, 2008 at 7:00 AM by: Matthew Linden </Text>
  </Block>
  <Block left="275" top="1822" right="715" bottom="1858" depth="19">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="7.2" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#546368" />
    </Attributes>
    <Text>[UPDATE 11:14 a.m. PST - rika] The problem has been resolved. Thank you for your patience with this issue.</Text>
  </Block>
  <Block left="275" top="1881" right="715" bottom="1935" depth="19">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="7.2" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#546368" />
    </Attributes>
    <Text>[UPDATE 8:20 a.m. PST –teeple] There’s a Linden network engineer at the co-location site this morning; hopefully this will be resolved very shortly. We apologize for the protracted inconvenience.</Text>
  </Block>
  <Block left="275" top="1958" right="715" bottom="1976" depth="19">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="7.2" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#546368" />
    </Attributes>
    <Text>***</Text>
  </Block>
  <Block left="275" top="2001" right="695" bottom="2033" depth="20">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="7.2" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#808080" />
    </Attributes>
    <Text>We have identified that, due to some network issues, around 480 regions are currently unreachable by residents.</Text>
  </Block>
  <Block left="275" top="2060" right="713" bottom="2092" depth="20">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="7.2" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#808080" />
    </Attributes>
    <Text>We’re sorry for this inconvenience but be assured that we’re actively working on this right now.</Text>
  </Block>
  <Block left="274" top="2129" right="628" bottom="2161" depth="29">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="6.75" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#777777" />
    </Attributes>
    <Text>Categories: Announcements &amp; News, Concierge, Resident Experience, Service Status</Text>
  </Block>
  <Block left="685" top="2145" right="701" bottom="2161" depth="31">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="7.2" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#4378a4" />
    </Attributes>
    <Text>off</Text>
  </Block>
  <Block left="268" top="2213" right="722" bottom="2284" depth="17">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="7.2" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#546368" />
    </Attributes>
    <Text>[RESOLVED] Events page not allowing residents to add new events
Monday, March 10th, 2008 at 2:49 AM by: Matthew Linden </Text>
  </Block>
  <Block left="275" top="2307" right="715" bottom="2343" depth="19">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="7.2" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#546368" />
    </Attributes>
    <Text>[RESOLVED - 12:30pm PST] The issue has been resolved and you should be able to post events as normal.</Text>
  </Block>
  <Block left="275" top="2366" right="715" bottom="2420" depth="19">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="7.2" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#546368" />
    </Attributes>
    <Text>It appears that residents are unable to add forthcoming events to our Events page at the moment. Sincere apologies for that. We’ll try to get that resolved as soon as we can.</Text>
  </Block>
  <Block left="275" top="2443" right="715" bottom="2461" depth="19">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="7.2" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#546368" />
    </Attributes>
    <Text>Best Wishes to you.</Text>
  </Block>
  <Block left="274" top="2496" right="656" bottom="2528" depth="29">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="6.75" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#777777" />
    </Attributes>
    <Text>Categories: -Miscellaneous, Customer Service, Resident Experience, Service Status, Website Status</Text>
  </Block>
  <Block left="685" top="2512" right="701" bottom="2528" depth="31">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="7.2" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#4378a4" />
    </Attributes>
    <Text>off</Text>
  </Block>
  <Block left="268" top="2580" right="722" bottom="2633" depth="17">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="7.2" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#546368" />
    </Attributes>
    <Text>[Resolved] In world services interrupted
Sunday, March 9th, 2008 at 11:44 AM by: Kate Linden </Text>
  </Block>
  <Block left="275" top="2656" right="715" bottom="2728" depth="19">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="7.2" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#546368" />
    </Attributes>
    <Text>[Resolved 3:15 PM] Let’s try this again!  The database is happy again and all in world services are clear to resume.  Please give some time for transactions to catch up. If you still have a transaction that did not go through, please submit a support ticket.</Text>
  </Block>
  <Block left="275" top="2751" right="715" bottom="2787" depth="19">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="7.2" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#546368" />
    </Attributes>
    <Text>[Update 2:47 PM] This issue is not yet resolved. Please continue to refrain from conducting Land and L$ transactions.</Text>
  </Block>
  <Block left="275" top="2810" right="715" bottom="2846" depth="19">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="7.2" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#546368" />
    </Attributes>
    <Text>[Update 2:19 PM] In world services are beginning to resume. Some transactions were delayed and are catching up.</Text>
  </Block>
  <Block left="275" top="2869" right="715" bottom="2923" depth="19">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="7.2" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#546368" />
    </Attributes>
    <Text>[Update 1:58 PM] Residents are reporting in world services are not all functioning yet. We are looking into this and will update you as soon as we have information.</Text>
  </Block>
  <Block left="275" top="2946" right="715" bottom="3000" depth="19">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="7.2" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#546368" />
    </Attributes>
    <Text>[Update 1:26 PM] In world services have resumed. You are clear to conduct Land and L$ transactions again. Thank you for your cooperation.</Text>
  </Block>
  <Block left="275" top="3023" right="715" bottom="3059" depth="19">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="7.2" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#546368" />
    </Attributes>
    <Text>[Update 12:48 PM] Please refrain from land and L$ transactions until we give an all clear.</Text>
  </Block>
  <Block left="275" top="3082" right="715" bottom="3136" depth="19">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="7.2" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#546368" />
    </Attributes>
    <Text>We are experiencing a temporary interruption of In World Services which include Teleporting, L$ Balance loading, groups not loading. We are working to correct this and will update you shortly.</Text>
  </Block>
  <Block left="274" top="3171" right="626" bottom="3203" depth="29">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="6.75" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#777777" />
    </Attributes>
    <Text>Categories: -Miscellaneous, Bugs &amp; Fixes, Customer Service, Resident Experience, Service Status</Text>
  </Block>
  <Block left="685" top="3187" right="701" bottom="3203" depth="31">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="7.2" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#4378a4" />
    </Attributes>
    <Text>off</Text>
  </Block>
  <Block left="268" top="3255" right="722" bottom="3308" depth="17">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="7.2" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#546368" />
    </Attributes>
    <Text>What are you doing next Saturday?
Saturday, March 8th, 2008 at 2:01 PM by: harmonylinden </Text>
  </Block>
  <Block left="275" top="3331" right="715" bottom="3403" depth="19">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="7.2" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#546368" />
    </Attributes>
    <Text>We’d like to invite all adult Second Life concierge-level residents to join us for a party on March 15th! Instead of celebrating the Ides of March by killing Caesar, come and hang out with the Concierge team and other concierge customers.</Text>
  </Block>
  <Block left="275" top="3428" right="453" bottom="3442" depth="20">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="7.2" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#4378a4" />
    </Attributes>
    <Text>Read the rest of this entry »</Text>
  </Block>
  <Block left="274" top="3487" right="390" bottom="3502" depth="29">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="6.75" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#777777" />