<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE Page [
<!ELEMENT Page (Block)*>
<!ELEMENT Block (Attributes, Text)>
<!ATTLIST Block
  left   CDATA   #REQUIRED
  top    CDATA   #REQUIRED
  right  CDATA   #REQUIRED
  bottom CDATA   #REQUIRED
  depth  CDATA   #REQUIRED
>
<!ELEMENT Attributes (Attribute)*>
<!ELEMENT Attribute EMPTY>
<!ATTLIST Attribute
  name   NMTOKEN #REQUIRED
  value  CDATA   #REQUIRED
>
<!ELEMENT Text (#PCDATA)>
]>

<Page>

  <Block left="159" top="40" right="766" bottom="65" depth="5">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="12.15" />
      <Attribute name="realFontWeight" value="700" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>Bruce Schneier</Text>
  </Block>
  <Block left="25" top="105" right="119" bottom="134" depth="5">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="7.05" />
      <Attribute name="realFontWeight" value="700" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>Home </Text>
  </Block>
  <Block left="25" top="134" right="119" bottom="163" depth="5">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="7.05" />
      <Attribute name="realFontWeight" value="700" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>Blog </Text>
  </Block>
  <Block left="25" top="163" right="119" bottom="206" depth="5">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="7.05" />
      <Attribute name="realFontWeight" value="700" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>Crypto-Gram Newsletter </Text>
  </Block>
  <Block left="25" top="206" right="119" bottom="235" depth="5">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="7.05" />
      <Attribute name="realFontWeight" value="700" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>Books </Text>
  </Block>
  <Block left="25" top="235" right="119" bottom="278" depth="5">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="7.05" />
      <Attribute name="realFontWeight" value="700" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>Essays and Op Eds </Text>
  </Block>
  <Block left="25" top="278" right="119" bottom="335" depth="5">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="7.05" />
      <Attribute name="realFontWeight" value="700" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>Computer Security Articles </Text>
  </Block>
  <Block left="25" top="335" right="119" bottom="378" depth="5">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="7.05" />
      <Attribute name="realFontWeight" value="700" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>News and Interviews </Text>
  </Block>
  <Block left="25" top="378" right="119" bottom="421" depth="5">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="7.05" />
      <Attribute name="realFontWeight" value="700" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>Audio and Video </Text>
  </Block>
  <Block left="25" top="421" right="119" bottom="464" depth="5">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="7.05" />
      <Attribute name="realFontWeight" value="700" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>Speaking Schedule </Text>
  </Block>
  <Block left="25" top="464" right="119" bottom="507" depth="5">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="7.05" />
      <Attribute name="realFontWeight" value="700" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>Password Safe </Text>
  </Block>
  <Block left="25" top="507" right="119" bottom="578" depth="5">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="7.05" />
      <Attribute name="realFontWeight" value="700" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>Cryptography and Computer Security Resources </Text>
  </Block>
  <Block left="25" top="578" right="119" bottom="621" depth="5">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="7.05" />
      <Attribute name="realFontWeight" value="700" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>Contact Information </Text>
  </Block>
  <Block left="159" top="99" right="766" bottom="121" depth="5">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="10.65" />
      <Attribute name="realFontWeight" value="700" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>Schneier on Security</Text>
  </Block>
  <Block left="159" top="125" right="766" bottom="141" depth="5">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="7.6" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>A blog covering security and security technology.</Text>
  </Block>
  <Block left="159" top="160" right="766" bottom="178" depth="5">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="9.1" />
      <Attribute name="realFontWeight" value="700" />
      <Attribute name="realTextColor" value="#800000" />
    </Attributes>
    <Text>Privacy and Power</Text>
  </Block>
  <Block left="159" top="180" right="766" bottom="292" depth="5">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="7.6" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>When I write and speak about privacy, I am regularly confronted with the mutual disclosure argument. Explained in books like David Brin&apos;s The Transparent Society, the argument goes something like this: In a world of ubiquitous surveillance, you&apos;ll know all about me, but I will also know all about you. The government will be watching us, but we&apos;ll also be watching the government. This is different than before, but it&apos;s not automatically worse. And because I know your secrets, you can&apos;t use my secrets as a weapon against me.</Text>
  </Block>
  <Block left="159" top="305" right="766" bottom="369" depth="5">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="7.6" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>This might not be everybody&apos;s idea of utopia -- and it certainly doesn&apos;t address the inherent value of privacy -- but this theory has a glossy appeal, and could easily be mistaken for a way out of the problem of technology&apos;s continuing erosion of privacy. Except it doesn&apos;t work, because it ignores the crucial dissimilarity of power. </Text>
  </Block>
  <Block left="159" top="382" right="766" bottom="414" depth="5">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="7.6" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>You cannot evaluate the value of privacy and disclosure unless you account for the relative power levels of the discloser and the disclosee.</Text>
  </Block>
  <Block left="159" top="427" right="766" bottom="491" depth="5">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="7.6" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>If I disclose information to you, your power with respect to me increases. One way to address this power imbalance is for you to similarly disclose information to me. We both have less privacy, but the balance of power is maintained. But this mechanism fails utterly if you and I have different power levels to begin with. </Text>
  </Block>
  <Block left="159" top="504" right="766" bottom="600" depth="5">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="7.6" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>An example will make this clearer. You&apos;re stopped by a police officer, who demands to see identification. Divulging your identity will give the officer enormous power over you: He or she can search police databases using the information on your ID; he or she can create a police record attached to your name; he or she can put you on this or that secret terrorist watch list. Asking to see the officer&apos;s ID in return gives you no comparable power over him or her. The power imbalance is too great, and mutual disclosure does not make it OK.</Text>
  </Block>
  <Block left="159" top="613" right="766" bottom="661" depth="5">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="7.6" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>You can think of your existing power as the exponent in an equation that determines the value, to you, of more information. The more power you have, the more additional power you derive from the new data.</Text>
  </Block>
  <Block left="159" top="674" right="766" bottom="706" depth="5">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="7.6" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>Another example: When your doctor says &quot;take off your clothes,&quot; it makes no sense for you to say, &quot;You first, doc.&quot; The two of you are not engaging in an interaction of equals.</Text>
  </Block>
  <Block left="159" top="719" right="766" bottom="831" depth="5">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="7.6" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>This is the principle that should guide decision-makers when they consider installing surveillance cameras or launching data-mining programs. It&apos;s not enough to open the efforts to public scrutiny. All aspects of government work best when the relative power between the governors and the governed remains as small as possible -- when liberty is high and control is low. Forced openness in government reduces the relative power differential between the two, and is generally good. Forced openness in laypeople increases the relative power, and is generally bad.</Text>
  </Block>
  <Block left="159" top="844" right="766" bottom="924" depth="5">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="7.6" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>Seventeen-year-old Erik Crespo was arrested in 2005 in connection with a shooting in a New York City elevator. There&apos;s no question that he committed the shooting; it was captured on surveillance-camera videotape. But he claimed that while being interrogated, Detective Christopher Perino tried to talk him out of getting a lawyer, and told him that he had to sign a confession before he could see a judge.</Text>
  </Block>
  <Block left="159" top="937" right="766" bottom="1017" depth="5">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="7.6" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>Perino denied, under oath, that he ever questioned Crespo. But Crespo had received an MP3 player as a Christmas gift, and surreptitiously recorded the questioning. The defense brought a transcript and CD into evidence. Shortly thereafter, the prosecution offered Crespo a better deal than originally proffered (seven years rather than 15). Crespo took the deal, and Perino was separately indicted on charges of perjury.</Text>
  </Block>
  <Block left="159" top="1030" right="766" bottom="1142" depth="5">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="7.6" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>Without that recording, it was the detective&apos;s word against Crespo&apos;s. And who would believe a murder suspect over a New York City detective? That power imbalance was reduced only because Crespo was smart enough to press the &quot;record&quot; button on his MP3 player. Why aren&apos;t all interrogations recorded? Why don&apos;t defendants have the right to those recordings, just as they have the right to an attorney? Police routinely record traffic stops from their squad cars for their own protection; that video record shouldn&apos;t stop once the suspect is no longer a threat.</Text>
  </Block>
  <Block left="159" top="1155" right="766" bottom="1219" depth="5">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="7.6" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>Cameras make sense when trained on police, and in offices where lawmakers meet with lobbyists, and wherever government officials wield power over the people. Open-government laws, giving the public access to government records and meetings of governmental bodies, also make sense. These all foster liberty. </Text>
  </Block>
  <Block left="159" top="1232" right="766" bottom="1296" depth="5">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="7.6" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>Ubiquitous surveillance programs that affect everyone without probable cause or warrant, like the National Security Agency&apos;s warrantless eavesdropping programs or various proposals to monitor everything on the internet, foster control. And no one is safer in a political system of control.</Text>
  </Block>
  <Block left="159" top="1309" right="766" bottom="1325" depth="5">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="7.6" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>This essay originally appeared on Wired.com.</Text>
  </Block>
  <Block left="159" top="1336" right="766" bottom="1349" depth="5">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="6.55" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>Posted on March 11, 2008 at 06:09 AM • 14 Comments • 1 Blog Reaction </Text>
  </Block>
  <Block left="159" top="1384" right="766" bottom="1402" depth="5">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="9.1" />
      <Attribute name="realFontWeight" value="700" />
      <Attribute name="realTextColor" value="#800000" />
    </Attributes>
    <Text>Israel Implementing IFF System for Commercial Aircraft</Text>
  </Block>
  <Block left="159" top="1404" right="766" bottom="1436" depth="5">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="7.6" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>Israel is implementing an IFF (identification, friend or foe) system for commercial aircraft, designed to differentiate legitimate planes from terrorist-controlled planes.</Text>
  </Block>
  <Block left="159" top="1449" right="766" bottom="1529" depth="5">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="7.6" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>The news article implies that it&apos;s a basic challenge-and-response system. Ground control issues some kind of alphanumeric challenge to the plane. The pilot types the challenge into some hand-held computer device, and reads back the reply. Authentication is achieved by 1) physical possession of the device, and 2) typing a legitimate PIN into the device to activate it.</Text>
  </Block>
  <Block left="159" top="1542" right="766" bottom="1590" depth="5">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="7.6" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>The article talks about a distress mode, where the pilot signals that a terrorist is holding a gun to his head. Likely, that&apos;s done by typing a special distress PIN into the device, and reading back whatever the screen displays.</Text>
  </Block>
  <Block left="159" top="1603" right="766" bottom="1667" depth="5">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="7.6" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>The military has had this sort of system -- first paper-based, and eventually computer-based -- for decades. The critical issue with using this on commercial aircraft is how to deal with user error. The system has to be easy enough to use, and the parts hard enough to lose, that there won&apos;t be a lot of false alarms.</Text>
  </Block>
  <Block left="159" top="1678" right="766" bottom="1691" depth="5">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="6.55" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>Posted on March 10, 2008 at 12:24 PM • 32 Comments • 3 Blog Reactions </Text>
  </Block>
  <Block left="159" top="1726" right="766" bottom="1744" depth="5">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="9.1" />
      <Attribute name="realFontWeight" value="700" />
      <Attribute name="realTextColor" value="#800000" />
    </Attributes>
    <Text>Security Products: Suites vs. Best-of-Breed</Text>
  </Block>
  <Block left="159" top="1746" right="766" bottom="1826" depth="5">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="7.6" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>We know what we don&apos;t like about buying consolidated product suites: one great product and a bunch of mediocre ones. And we know what we don&apos;t like about buying best-of-breed: multiple vendors, multiple interfaces, and multiple products that don&apos;t work well together. The security industry has gone back and forth between the two, as a new generation of IT security professionals rediscovers the downsides of each solution. </Text>
  </Block>
  <Block left="159" top="1839" right="766" bottom="1887" depth="5">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="7.6" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>The real problem is that neither solution really works, and we continually fool ourselves into believing whatever we don&apos;t have is better than what we have at the time. And the real solution is to buy results, not products. </Text>
  </Block>
  <Block left="159" top="1900" right="766" bottom="1980" depth="5">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="7.6" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>Honestly, no one wants to buy IT security. People want to buy whatever they want -- connectivity, a Web presence, email, networked applications, whatever -- and they want it to be secure. That they&apos;re forced to spend money on IT security is an artifact of the youth of the computer industry. And sooner or later the need to buy security will disappear. </Text>
  </Block>
  <Block left="159" top="1993" right="766" bottom="2073" depth="5">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="7.6" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>It will disappear because IT vendors are starting to realize they have to provide security as part of whatever they&apos;re selling. It will disappear because organizations are starting to buy services instead of products, and demanding security as part of those services. It will disappear because the security industry will disappear as a consumer category, and will instead market to the IT industry. </Text>
  </Block>
  <Block left="159" top="2086" right="766" bottom="2198" depth="5">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="7.6" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>The critical driver here is outsourcing. Outsourcing is the ultimate consolidator, because the customer no longer cares about the details. If I buy my network services from a large IT infrastructure company, I don&apos;t care if it secures things by installing the hot new intrusion prevention systems, by configuring the routers and servers as to obviate the need for network-based security, or if it uses magic security dust given to it by elven kings. I just want a contract that specifies a level and quality of service, and my vendor can figure it out. </Text>
  </Block>
  <Block left="159" top="2211" right="766" bottom="2243" depth="5">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="7.6" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>IT is infrastructure. Infrastructure is always outsourced. And the details of how the infrastructure works are left to the companies that provide it. </Text>
  </Block>
  <Block left="159" top="2256" right="766" bottom="2368" depth="5">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="7.6" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>This is the future of IT, and when that happens we&apos;re going to start to see a type of consolidation we haven&apos;t seen before. Instead of large security companies gobbling up small security companies, both large and small security companies will be gobbled up by non-security companies. It&apos;s already starting to happen. In 2006, IBM bought ISS. The same year BT bought my company, Counterpane, and last year it bought INS. These aren&apos;t large security companies buying small security companies; these are non-security companies buying large and small security companies. </Text>
  </Block>
  <Block left="159" top="2381" right="766" bottom="2397" depth="5">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="7.6" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>If I were Symantec and McAfee, I would be preparing myself for a buyer. </Text>
  </Block>
  <Block left="159" top="2410" right="766" bottom="2474" depth="5">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="7.6" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>This is good consolidation. Instead of having to choose between a single product suite that isn&apos;t very good or a best-of-breed set of products that don&apos;t work well together, we can ignore the issue completely. We can just find an infrastructure provider that will figure it out and make it work -- who cares how?</Text>
  </Block>
  <Block left="159" top="2487" right="766" bottom="2519" depth="5">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="7.6" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>This essay originally appeared as the second half of a point/counterpoint with Marcus Ranum in Information Security. Here&apos;s Marcus&apos;s half.</Text>
  </Block>
  <Block left="159" top="2530" right="766" bottom="2543" depth="5">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="6.55" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>Posted on March 10, 2008 at 06:33 AM • 24 Comments • 6 Blog Reactions </Text>
  </Block>
  <Block left="159" top="2578" right="766" bottom="2596" depth="5">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="9.1" />
      <Attribute name="realFontWeight" value="700" />
      <Attribute name="realTextColor" value="#800000" />
    </Attributes>
    <Text>Friday Squid Blogging: Squid T-Shirts</Text>
  </Block>
  <Block left="159" top="2598" right="766" bottom="2614" depth="5">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="7.6" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>Nice. Not as good.</Text>
  </Block>
  <Block left="159" top="2625" right="766" bottom="2638" depth="5">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="6.55" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>Posted on March 07, 2008 at 03:19 PM • 4 Comments • 7 Blog Reactions </Text>
  </Block>
  <Block left="159" top="2673" right="766" bottom="2691" depth="5">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="9.1" />
      <Attribute name="realFontWeight" value="700" />
      <Attribute name="realTextColor" value="#800000" />
    </Attributes>
    <Text>Me in the News</Text>
  </Block>
  <Block left="159" top="2693" right="766" bottom="2725" depth="5">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="7.6" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>I had an op-ed published in the Minneapolis Star Tribune on national ID, and they also ran a small Q&amp;A.</Text>
  </Block>