<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE Page [
<!ELEMENT Page (Block)*>
<!ELEMENT Block (Attributes, Text)>
<!ATTLIST Block
  left   CDATA   #REQUIRED
  top    CDATA   #REQUIRED
  right  CDATA   #REQUIRED
  bottom CDATA   #REQUIRED
  depth  CDATA   #REQUIRED
>
<!ELEMENT Attributes (Attribute)*>
<!ELEMENT Attribute EMPTY>
<!ATTLIST Attribute
  name   NMTOKEN #REQUIRED
  value  CDATA   #REQUIRED
>
<!ELEMENT Text (#PCDATA)>
]>

<Page>

  <Block left="783" top="88" right="974" bottom="111" depth="14">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="7.5" />
      <Attribute name="realFontWeight" value="700" />
      <Attribute name="realTextColor" value="#c0c0f0" />
    </Attributes>
    <Text>Schnellsuche:    </Text>
  </Block>
  <Block left="2" top="114" right="994" bottom="132" depth="6">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="7.5" />
      <Attribute name="realFontWeight" value="700" />
      <Attribute name="realTextColor" value="#c0c0f0" />
    </Attributes>
    <Text>  FAQ | Suchen | Mitgliederliste | Benutzergruppen | Statistiken | Profil | Einloggen, um private Nachrichten zu lesen | Login | Registrieren </Text>
  </Block>
  <Block left="17" top="191" right="333" bottom="203" depth="9">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="6" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>Aktuelles Datum und Uhrzeit: Di März 11, 2008 8:57 am</Text>
  </Block>
  <Block left="17" top="203" right="226" bottom="216" depth="10">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="6.6" />
      <Attribute name="realFontWeight" value="700" />
      <Attribute name="realTextColor" value="#663399" />
    </Attributes>
    <Text>Gentoo Forums Foren-Übersicht</Text>
  </Block>
  <Block left="570" top="161" right="981" bottom="218" depth="8">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="6" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>Unbeantwortete Beiträge anzeigen
Beiträge der letzten 24 Stunden anzeigen

 </Text>
  </Block>
  <Block left="51" top="238" right="733" bottom="263" depth="12">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#46357c" />
      <Attribute name="realFontSize" value="6.6" />
      <Attribute name="realFontWeight" value="700" />
      <Attribute name="realTextColor" value="#efefef" />
    </Attributes>
    <Text>Neueste Meldungen</Text>
  </Block>
  <Block left="822" top="235" right="978" bottom="265" depth="8">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#46357c" />
      <Attribute name="realFontSize" value="6.6" />
      <Attribute name="realFontWeight" value="700" />
      <Attribute name="realTextColor" value="#efefef" />
    </Attributes>
    <Text> Letzter Beitrag </Text>
  </Block>
  <Block left="51" top="270" right="333" bottom="283" depth="10">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="6.6" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#663399" />
    </Attributes>
    <Text>[ GLSA 200803-18 ] Cacti: Multiple vulnerabilities</Text>
  </Block>
  <Block left="824" top="271" right="976" bottom="283" depth="9">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="6" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>Mo März 10, 2008 6:26 pm</Text>
  </Block>
  <Block left="51" top="293" right="353" bottom="306" depth="10">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="6.6" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#663399" />
    </Attributes>
    <Text>[ GLSA 200803-17 ] PDFlib: Multiple buffer overflows</Text>
  </Block>
  <Block left="824" top="294" right="976" bottom="306" depth="9">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="6" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>Mo März 10, 2008 5:26 pm</Text>
  </Block>
  <Block left="51" top="316" right="363" bottom="329" depth="10">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="6.6" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#663399" />
    </Attributes>
    <Text>[ GLSA 200803-16 ] MPlayer: Multiple buffer overflows</Text>
  </Block>
  <Block left="824" top="317" right="976" bottom="329" depth="9">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="6" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>Mo März 10, 2008 4:26 pm</Text>
  </Block>
  <Block left="18" top="354" right="681" bottom="382" depth="8">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#46357c" />
      <Attribute name="realFontSize" value="6.6" />
      <Attribute name="realFontWeight" value="700" />
      <Attribute name="realTextColor" value="#efefef" />
    </Attributes>
    <Text> Forum </Text>
  </Block>
  <Block left="682" top="354" right="746" bottom="382" depth="8">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#46357c" />
      <Attribute name="realFontSize" value="6.6" />
      <Attribute name="realFontWeight" value="700" />
      <Attribute name="realTextColor" value="#efefef" />
    </Attributes>
    <Text> Themen </Text>
  </Block>
  <Block left="747" top="354" right="814" bottom="382" depth="8">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#46357c" />
      <Attribute name="realFontSize" value="6.6" />
      <Attribute name="realFontWeight" value="700" />
      <Attribute name="realTextColor" value="#efefef" />
    </Attributes>
    <Text> Beiträge </Text>
  </Block>
  <Block left="815" top="354" right="978" bottom="382" depth="8">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#46357c" />
      <Attribute name="realFontSize" value="6.6" />
      <Attribute name="realFontWeight" value="700" />
      <Attribute name="realTextColor" value="#efefef" />
    </Attributes>
    <Text> Letzter Beitrag </Text>
  </Block>
  <Block left="21" top="390" right="100" bottom="404" depth="10">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="7.2" />
      <Attribute name="realFontWeight" value="700" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>Assistance</Text>
  </Block>
  <Block left="74" top="417" right="233" bottom="431" depth="10">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="7.2" />
      <Attribute name="realFontWeight" value="700" />
      <Attribute name="realTextColor" value="#663399" />
    </Attributes>
    <Text>News &amp; Announcements</Text>
  </Block>
  <Block left="74" top="431" right="439" bottom="444" depth="10">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="6.6" />
      <Attribute name="realFontWeight" value="700" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>Read this before submitting your first post to any forum</Text>
  </Block>
  <Block left="74" top="444" right="238" bottom="456" depth="9">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="6" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>Moderator Global Moderators</Text>
  </Block>
  <Block left="700" top="431" right="728" bottom="443" depth="9">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="6" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>1624</Text>
  </Block>
  <Block left="766" top="431" right="794" bottom="443" depth="9">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="6" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>1674</Text>
  </Block>
  <Block left="820" top="425" right="972" bottom="449" depth="9">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="6" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>Mo März 10, 2008 6:26 pm
GLSA </Text>
  </Block>
  <Block left="74" top="468" right="259" bottom="482" depth="10">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="7.2" />
      <Attribute name="realFontWeight" value="700" />
      <Attribute name="realTextColor" value="#663399" />
    </Attributes>
    <Text>Frequently Asked Questions</Text>
  </Block>
  <Block left="74" top="482" right="606" bottom="495" depth="9">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="6.6" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>Some of the most commonly heard questions in the Gentoo Community, along with answers.</Text>
  </Block>
  <Block left="74" top="495" right="238" bottom="507" depth="9">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="6" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>Moderator Global Moderators</Text>
  </Block>
  <Block left="707" top="482" right="721" bottom="494" depth="9">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="6" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>81</Text>
  </Block>
  <Block left="770" top="482" right="791" bottom="494" depth="9">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="6" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>102</Text>
  </Block>
  <Block left="821" top="476" right="971" bottom="500" depth="9">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="6" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>So Jun 03, 2007 11:26 pm
cynric </Text>
  </Block>
  <Block left="74" top="514" right="187" bottom="528" depth="10">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="7.2" />
      <Attribute name="realFontWeight" value="700" />
      <Attribute name="realTextColor" value="#663399" />
    </Attributes>
    <Text>Installing Gentoo</Text>
  </Block>
  <Block left="74" top="528" right="673" bottom="567" depth="9">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="6.6" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>Problems with the Installer? Having non-GUI problems with the Installation Guide? If you&apos;re still working your way through it, or just need some info before you start your install, this is the place. All other questions go elsewhere.</Text>
  </Block>
  <Block left="74" top="567" right="238" bottom="579" depth="9">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="6" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>Moderator Global Moderators</Text>
  </Block>
  <Block left="696" top="540" right="731" bottom="552" depth="9">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="6" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>43874</Text>
  </Block>
  <Block left="759" top="540" right="801" bottom="552" depth="9">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="6" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>272305</Text>
  </Block>
  <Block left="823" top="534" right="970" bottom="558" depth="9">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="6" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>Di März 11, 2008 6:18 am
gentoo_newguy </Text>
  </Block>
  <Block left="74" top="580" right="146" bottom="594" depth="10">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="7.2" />
      <Attribute name="realFontWeight" value="700" />
      <Attribute name="realTextColor" value="#663399" />
    </Attributes>
    <Text>Multimedia</Text>
  </Block>
  <Block left="74" top="594" right="671" bottom="620" depth="9">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="6.6" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>Help with creation, editing, or playback of sounds, images, or video. Amarok, audacious, mplayer, grip, cdparanoia and anything else that makes a sound or plays a video.</Text>
  </Block>
  <Block left="74" top="620" right="309" bottom="632" depth="9">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="6" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>Moderatoren beandog, Global Moderators</Text>
  </Block>
  <Block left="696" top="600" right="731" bottom="612" depth="9">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="6" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>36242</Text>
  </Block>
  <Block left="759" top="600" right="801" bottom="612" depth="9">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="6" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>198649</Text>
  </Block>
  <Block left="823" top="594" right="970" bottom="618" depth="9">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="6" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>Di März 11, 2008 7:19 am
fuzzybee </Text>
  </Block>
  <Block left="74" top="633" right="222" bottom="647" depth="10">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="7.2" />
      <Attribute name="realFontWeight" value="700" />
      <Attribute name="realTextColor" value="#663399" />
    </Attributes>
    <Text>Desktop Environments</Text>
  </Block>
  <Block left="74" top="647" right="679" bottom="673" depth="9">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="6.6" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>Problems with GUI applications? Questions about X, KDE, Gnome, Fluxbox, etc.? Come on in. NOTE: For multimedia, go up one forum</Text>
  </Block>
  <Block left="74" top="673" right="238" bottom="685" depth="9">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="6" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>Moderator Global Moderators</Text>
  </Block>
  <Block left="696" top="653" right="731" bottom="665" depth="9">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="6" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>73909</Text>
  </Block>
  <Block left="759" top="653" right="801" bottom="665" depth="9">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="6" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>446295</Text>
  </Block>
  <Block left="823" top="647" right="970" bottom="671" depth="9">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="6" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>Di März 11, 2008 8:24 am
tomas.pulai </Text>
  </Block>
  <Block left="74" top="686" right="224" bottom="700" depth="10">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="7.2" />
      <Attribute name="realFontWeight" value="700" />
      <Attribute name="realTextColor" value="#663399" />
    </Attributes>
    <Text>Networking &amp; Security</Text>
  </Block>
  <Block left="74" top="700" right="668" bottom="726" depth="9">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="6.6" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>Having problems getting connected to the internet or running a server? Wondering about securing your box? Ask here.</Text>
  </Block>
  <Block left="74" top="726" right="238" bottom="738" depth="9">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="6" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>Moderator Global Moderators</Text>
  </Block>
  <Block left="696" top="706" right="731" bottom="718" depth="9">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="6" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>58978</Text>
  </Block>
  <Block left="759" top="706" right="801" bottom="718" depth="9">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="6" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>305337</Text>
  </Block>
  <Block left="823" top="700" right="970" bottom="724" depth="9">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="6" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>Di März 11, 2008 8:00 am
Freekazonid </Text>
  </Block>
  <Block left="74" top="739" right="201" bottom="753" depth="10">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="7.2" />
      <Attribute name="realFontWeight" value="700" />
      <Attribute name="realTextColor" value="#663399" />
    </Attributes>
    <Text>Kernel &amp; Hardware</Text>
  </Block>
  <Block left="74" top="753" right="679" bottom="779" depth="9">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="6.6" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>Kernel not recognizing your hardware? Problems with power management or PCMCIA? What hardware is compatible with Gentoo? See here. (Only for kernels supported by Gentoo.)</Text>
  </Block>
  <Block left="74" top="779" right="238" bottom="791" depth="9">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="6" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>Moderator Global Moderators</Text>
  </Block>
  <Block left="696" top="759" right="731" bottom="771" depth="9">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="6" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>53020</Text>
  </Block>
  <Block left="759" top="759" right="801" bottom="771" depth="9">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="6" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>305570</Text>
  </Block>
  <Block left="823" top="753" right="970" bottom="777" depth="9">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="6" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>Di März 11, 2008 8:48 am
marcogrego </Text>
  </Block>
  <Block left="74" top="792" right="233" bottom="806" depth="10">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="7.2" />
      <Attribute name="realFontWeight" value="700" />
      <Attribute name="realTextColor" value="#663399" />
    </Attributes>
    <Text>Portage &amp; Programming</Text>
  </Block>
  <Block left="74" top="806" right="647" bottom="832" depth="9">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="6.6" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>Problems with emerge or ebuilds? Have a basic programming question about C, PHP, Perl, BASH or something else?</Text>
  </Block>
  <Block left="74" top="832" right="238" bottom="844" depth="9">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="6" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>Moderator Global Moderators</Text>
  </Block>
  <Block left="696" top="812" right="731" bottom="824" depth="9">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="6" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>68822</Text>
  </Block>
  <Block left="759" top="812" right="801" bottom="824" depth="9">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="6" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>361836</Text>
  </Block>
  <Block left="823" top="806" right="970" bottom="830" depth="9">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="6" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>Di März 11, 2008 7:29 am
sammy2ooo </Text>
  </Block>
  <Block left="74" top="850" right="193" bottom="864" depth="10">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="7.2" />
      <Attribute name="realFontWeight" value="700" />
      <Attribute name="realTextColor" value="#663399" />
    </Attributes>
    <Text>Gamers &amp; Players</Text>
  </Block>
  <Block left="74" top="864" right="673" bottom="877" depth="9">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="6.6" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>Having problems getting your favorite Linux game to work? Want to discuss strategies? This is the place!</Text>
  </Block>
  <Block left="74" top="877" right="238" bottom="889" depth="9">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="6" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>Moderator Global Moderators</Text>
  </Block>
  <Block left="696" top="864" right="731" bottom="876" depth="9">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="6" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>11469</Text>
  </Block>
  <Block left="763" top="864" right="798" bottom="876" depth="9">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="6" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>90775</Text>
  </Block>
  <Block left="823" top="858" right="970" bottom="882" depth="9">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="6" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>Di März 11, 2008 7:37 am
gentoo_newguy </Text>
  </Block>
  <Block left="74" top="896" right="210" bottom="910" depth="10">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="7.2" />
      <Attribute name="realFontWeight" value="700" />
      <Attribute name="realTextColor" value="#663399" />
    </Attributes>
    <Text>Other Things Gentoo</Text>
  </Block>
  <Block left="74" top="910" right="670" bottom="936" depth="9">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="6.6" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>Still need help with Gentoo, and your question doesn&apos;t fit in the above forums? Here is your last bastion of hope.</Text>
  </Block>
  <Block left="74" top="936" right="238" bottom="948" depth="9">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="6" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>Moderator Global Moderators</Text>
  </Block>
  <Block left="696" top="916" right="731" bottom="928" depth="9">
    <Attributes>