<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!DOCTYPE Page [
<!ELEMENT Page (Block)*>
<!ELEMENT Block (Attributes, Text)>
<!ATTLIST Block
  left   CDATA   #REQUIRED
  top    CDATA   #REQUIRED
  right  CDATA   #REQUIRED
  bottom CDATA   #REQUIRED
  depth  CDATA   #REQUIRED
>
<!ELEMENT Attributes (Attribute)*>
<!ELEMENT Attribute EMPTY>
<!ATTLIST Attribute
  name   NMTOKEN #REQUIRED
  value  CDATA   #REQUIRED
>
<!ELEMENT Text (#PCDATA)>
]>

<Page>

  <Block left="24" top="4" right="130" bottom="26" depth="4">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="6" />
      <Attribute name="realFontWeight" value="700" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>Montag, 10.3.2008</Text>
  </Block>
  <Block left="233" top="6" right="302" bottom="24" depth="6">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="5.4" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#333333" />
    </Attributes>
    <Text>Schlagzeilen</Text>
  </Block>
  <Block left="302" top="4" right="384" bottom="26" depth="5">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="5.4" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>|TV-Programm</Text>
  </Block>
  <Block left="384" top="4" right="416" bottom="26" depth="5">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="5.4" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>|RSS</Text>
  </Block>
  <Block left="416" top="4" right="481" bottom="26" depth="5">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="5.4" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>|Newsletter</Text>
  </Block>
  <Block left="481" top="4" right="519" bottom="26" depth="5">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="5.4" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>|Mobil</Text>
  </Block>
  <Block left="519" top="4" right="569" bottom="26" depth="5">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="5.4" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>|Dienste</Text>
  </Block>
  <Block left="569" top="4" right="630" bottom="26" depth="5">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="5.4" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>|Startseite </Text>
  </Block>
  <Block left="630" top="4" right="691" bottom="26" depth="5">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="5.4" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>|Wetter</Text>
  </Block>
  <Block left="691" top="4" right="791" bottom="26" depth="5">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="5.4" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>|DER SPIEGEL </Text>
  </Block>
  <Block left="24" top="43" right="256" bottom="77" depth="4">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="10" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#ffffff" />
    </Attributes>
    <Text> 
SPIEGEL ONLINE</Text>
  </Block>
  <Block left="535" top="38" right="568" bottom="50" depth="5">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="8.3" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#ffffff" />
    </Attributes>
    <Text>Suche
   </Text>
  </Block>
  <Block left="24" top="87" right="118" bottom="106" depth="5">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="10" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#ffffff" />
    </Attributes>
    <Text>NACHRICHTEN </Text>
  </Block>
  <Block left="118" top="87" right="169" bottom="105" depth="5">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="10" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#ffffff" />
    </Attributes>
    <Text>VIDEO </Text>
  </Block>
  <Block left="169" top="87" right="231" bottom="105" depth="5">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="10" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#ffffff" />
    </Attributes>
    <Text>ENGLISH </Text>
  </Block>
  <Block left="231" top="87" right="315" bottom="105" depth="5">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="10" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#ffffff" />
    </Attributes>
    <Text>EINESTAGES </Text>
  </Block>
  <Block left="315" top="87" right="368" bottom="105" depth="5">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="10" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#ffffff" />
    </Attributes>
    <Text>FORUM </Text>
  </Block>
  <Block left="368" top="87" right="479" bottom="105" depth="5">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="10" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#ffffff" />
    </Attributes>
    <Text>SPIEGEL WISSEN </Text>
  </Block>
  <Block left="479" top="87" right="564" bottom="105" depth="5">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="10" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#ffffff" />
    </Attributes>
    <Text>ABO &amp; SHOP </Text>
  </Block>
  <Block left="24" top="106" right="68" bottom="134" depth="5">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="10" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>Home| </Text>
  </Block>
  <Block left="68" top="106" right="115" bottom="134" depth="5">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="10" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>Politik| 
Übersicht Deutschland Ausland </Text>
  </Block>
  <Block left="115" top="106" right="187" bottom="134" depth="5">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="10" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>Wirtschaft| 
Übersicht Börse Depot Fonds Derivate Placement24 Stellenmarkt </Text>
  </Block>
  <Block left="187" top="106" right="257" bottom="134" depth="5">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="10" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>Panorama| 
Übersicht Leute Justiz Zeitgeschichte </Text>
  </Block>
  <Block left="257" top="106" right="299" bottom="134" depth="5">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="10" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>Sport| 
Übersicht Fußball Wintersport Formel 1 US-Sports Achilles </Text>
  </Block>
  <Block left="299" top="106" right="345" bottom="134" depth="5">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="10" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>Kultur| 
Übersicht Kino Musik TV Bestseller Tageskarte Zwiebelfisch Matusseks Kulturtipp Gutenberg DesignKlicks SPIEGEL-Edition Veranstaltungen </Text>
  </Block>
  <Block left="345" top="106" right="406" bottom="134" depth="5">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="10" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>Netzwelt| 
Übersicht Web Tech Mobil Spielzeug Ehrensenf </Text>
  </Block>
  <Block left="406" top="106" right="494" bottom="134" depth="5">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="10" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>Wissenschaft| 
Übersicht Mensch &amp; Technik Natur Weltall </Text>
  </Block>
  <Block left="494" top="106" right="572" bottom="134" depth="5">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="10" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>UniSPIEGEL| 
Übersicht Studium Job &amp; Beruf WunderBAR </Text>
  </Block>
  <Block left="572" top="106" right="662" bottom="134" depth="5">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="10" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>SchulSPIEGEL| 
Übersicht Abi - und dann? Querweltein Leben U21 Wissen </Text>
  </Block>
  <Block left="662" top="106" right="704" bottom="134" depth="5">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="10" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>Reise| 
Übersicht Städtereisen Europa Fernweh km42 Datenbank Länderlexikon Skiatlas </Text>
  </Block>
  <Block left="704" top="106" right="738" bottom="134" depth="5">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="10" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>Auto 
Übersicht Tests Fahrkultur Automarkt Routenplaner </Text>
  </Block>
  <Block left="673" top="144" right="703" bottom="155" depth="5">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="6.2" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#990000" />
    </Attributes>
    <Text>Login</Text>
  </Block>
  <Block left="710" top="145" right="796" bottom="157" depth="4">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="6.2" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>Registrierung </Text>
  </Block>
  <Block left="28" top="338" right="204" bottom="367" depth="8">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="6.25" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#999999" />
    </Attributes>
    <Text>Foto: DPA</Text>
  </Block>
  <Block left="24" top="185" right="541" bottom="197" depth="4">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="6.25" />
      <Attribute name="realFontWeight" value="700" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>AUFTRITT DES SPD- CHEFS</Text>
  </Block>
  <Block left="218" top="205" right="542" bottom="252" depth="5">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="11.25" />
      <Attribute name="realFontWeight" value="700" />
      <Attribute name="realTextColor" value="#c11919" />
    </Attributes>
    <Text>CDU verlangt von Beck &quot;Ende des Eiertanzes&quot;</Text>
  </Block>
  <Block left="24" top="259" right="541" bottom="395" depth="4">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="7.5" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>Harsche Kritik an SPD-Chef Beck: CDU-Generalsekretär Pofalla misstraut dessen Versprechen, nach der Bundestagswahl 2009 nicht mit der Linken zu koalieren. Die Absage auf der ersten Pressekonferenz nach Becks Krankheit sei unglaubwürdig - auch FDP und Grüne sehen noch offene Fragen. mehr... [ Video | Forum ]</Text>
  </Block>
  <Block left="24" top="410" right="541" bottom="445" depth="5">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="7.5" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>Minutenprotokoll: Wie sich Beck beim ersten Auftritt nach der Krankheit schlug </Text>
  </Block>
  <Block left="24" top="445" right="541" bottom="463" depth="5">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="7.5" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>Analyse: Mehr Metzgers für Deutschland </Text>
  </Block>
  <Block left="24" top="463" right="541" bottom="481" depth="5">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="7.5" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>Koalitionen der Zukunft: Warum sich Grüne und FDP annähern müssen </Text>
  </Block>
  <Block left="24" top="481" right="541" bottom="499" depth="5">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="7.5" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>Hessen-Krise: Koch besteht auf Posten des Ministerpräsidenten </Text>
  </Block>
  <Block left="24" top="499" right="541" bottom="517" depth="5">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="7.5" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>Kanzlerkandidatur: SPD-Rechte fordern Beck zum Verzicht auf </Text>
  </Block>
  <Block left="24" top="517" right="541" bottom="535" depth="5">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="7.5" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>Quo vadis SPD?: 145 Jahre Selbstsuche  </Text>
  </Block>
  <Block left="24" top="571" right="541" bottom="583" depth="4">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="6.25" />
      <Attribute name="realFontWeight" value="700" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>LAFONTAINE- GATTIN</Text>
  </Block>
  <Block left="24" top="591" right="474" bottom="638" depth="5">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="11.25" />
      <Attribute name="realFontWeight" value="700" />
      <Attribute name="realTextColor" value="#c11919" />
    </Attributes>
    <Text>Christa Müller wirft Linksfraktion soziale Ungerechtigkeit vor</Text>
  </Block>
  <Block left="24" top="645" right="541" bottom="730" depth="4">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="7.5" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>Schlagabtausch bei den Linken: Familien-Sprecher Wunderlich wirft der Ehefrau seines Chefs vor, sie rede das Leid von Millionen Frauen klein. Christa Müller bleibt bei ihrem Vergleich vom Kampf gegen Krippenbetreuung und Genitalverstümmelung - und leitet den Gegenangriff ein. Von Sebastian Fischer mehr... [ Forum ]</Text>
  </Block>
  <Block left="24" top="766" right="541" bottom="778" depth="4">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="6.25" />
      <Attribute name="realFontWeight" value="700" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>TEAM- TRICK IM VORWAHLDRAMA</Text>
  </Block>
  <Block left="24" top="786" right="316" bottom="809" depth="5">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="11.25" />
      <Attribute name="realFontWeight" value="700" />
      <Attribute name="realTextColor" value="#c11919" />
    </Attributes>
    <Text>Obama in der Clinton- Falle</Text>
  </Block>
  <Block left="24" top="816" right="541" bottom="901" depth="4">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="7.5" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>Hillary und Bill Clinton schlagen ein Kandidaten-Tandem mit Barack Obama vor - doch was wie ein Friedensangebot klingt, ist kühle Strategie. Die frühere First Lady treibt ihren Rivalen in die Enge. Der Vorwahlkampf der Demokraten dürfte schmutziger werden. Aus Jackson, Mississippi, berichtet Gregor Peter Schmitz mehr... [ Forum ]</Text>
  </Block>
  <Block left="24" top="916" right="541" bottom="934" depth="5">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="7.5" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>Vorwahlen in Florida und Michigan: Clinton kämpft um die Phantom-Stimmen </Text>
  </Block>
  <Block left="24" top="934" right="541" bottom="952" depth="5">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="7.5" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>US-Vorwahlen: Obama lehnt Vizepräsidentschaft unter Clinton ab </Text>
  </Block>
  <Block left="24" top="952" right="541" bottom="987" depth="5">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="7.5" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>Nordirland-Konflikt: Nobelpreisträger Trimble hält Clinton für eine Aufschneiderin </Text>
  </Block>
  <Block left="24" top="1023" right="541" bottom="1035" depth="4">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="6.25" />
      <Attribute name="realFontWeight" value="700" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>MORDPROZESS</Text>
  </Block>
  <Block left="24" top="1043" right="468" bottom="1090" depth="5">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="11.25" />
      <Attribute name="realFontWeight" value="700" />
      <Attribute name="realTextColor" value="#c11919" />
    </Attributes>
    <Text>&quot;Da war ich plötzlich wütend, sehr, sehr wütend&quot;</Text>
  </Block>
  <Block left="24" top="1097" right="541" bottom="1165" depth="4">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="7.5" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>Fast 40 Jahre lang waren Ingrid und Horst Dieter C. aus Bergisch Gladbach verheiratet, doch eines Tages erdrosselte der Arbeitlose seine Frau, legte sie ins Bett, deckte sie zu. Vor Gericht begründete er heute die Tat: Er habe den ständigen Streit nicht mehr ausgehalten. Von Jörg Diehl, Köln mehr... </Text>
  </Block>
  <Block left="28" top="1354" right="204" bottom="1383" depth="8">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="6.25" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#999999" />
    </Attributes>
    <Text>Foto: Nasa/Davis</Text>
  </Block>
  <Block left="24" top="1201" right="541" bottom="1213" depth="4">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="6.25" />
      <Attribute name="realFontWeight" value="700" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>ASTEROIDEN- CRASHTEST</Text>
  </Block>
  <Block left="218" top="1221" right="503" bottom="1268" depth="5">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="11.25" />
      <Attribute name="realFontWeight" value="700" />
      <Attribute name="realTextColor" value="#c11919" />
    </Attributes>
    <Text>Forscher beschießen Mini- Erde im Labor</Text>
  </Block>
  <Block left="24" top="1275" right="541" bottom="1394" depth="4">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="7.5" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>Ein Asteroid stürzt auf die Erde, vernichtet das menschliche Leben - eine Horrorvision. Doch wie schlimm wäre ein Einschlag auf der Erde wirklich? Forscher machen jetzt den Crashtest: Mit einer Riesenkanone feuern sie im Labor auf eine simulierte Erdkugel. Von Jörg Kitzler mehr... [ Video ]</Text>
  </Block>
  <Block left="24" top="1409" right="541" bottom="1427" depth="5">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="7.5" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>Fotostrecke: Simulierte Asteroideneinschläge </Text>
  </Block>
  <Block left="28" top="1646" right="206" bottom="1672" depth="6">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="6.25" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#999999" />
    </Attributes>
    <Text>Hamburger Institut für Sozialforschung</Text>
  </Block>
  <Block left="24" top="1463" right="541" bottom="1475" depth="4">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="6.25" />
      <Attribute name="realFontWeight" value="700" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>NAZI- TÄTER</Text>
  </Block>
  <Block left="220" top="1483" right="486" bottom="1530" depth="5">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="11.25" />
      <Attribute name="realFontWeight" value="700" />
      <Attribute name="realTextColor" value="#c11919" />
    </Attributes>
    <Text>&quot;Ich zielte ruhig auf die Säuglinge&quot;</Text>
  </Block>
  <Block left="24" top="1537" right="541" bottom="1639" depth="4">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="7.5" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>Zahnärzte und Opernsänger, Lehrer und Schulschwänzer: Die Vernichtung der europäischen Juden war das Werk von rund 200.000 Deutschen und ihren Helfern. Warum wurden so viele Bürger zu Mördern? Von Georg Bönisch und Klaus Wiegrefe mehr... </Text>
  </Block>
  <Block left="24" top="1654" right="541" bottom="1689" depth="5">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="7.5" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>Väter als Täter: &quot;Geiseln in den Rücken geschossen&quot; </Text>
  </Block>
  <Block left="24" top="1689" right="541" bottom="1707" depth="5">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="7.5" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>Privatfotos aus Auschwitz: Fröhliche Stunden neben der Gaskammer </Text>
  </Block>
  <Block left="24" top="1707" right="541" bottom="1725" depth="5">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="7.5" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>Auschwitz-Befreiung: &quot;Wir trauten unseren Augen nicht&quot; </Text>
  </Block>
  <Block left="24" top="1725" right="541" bottom="1743" depth="5">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="7.5" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>Holocaust: Warum die Alliierten Auschwitz nicht bombardierten </Text>
  </Block>
  <Block left="24" top="1743" right="541" bottom="1761" depth="5">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="7.5" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>Video: Konzentrationslager unmittelbar nach der Befreiung </Text>
  </Block>
  <Block left="28" top="1980" right="206" bottom="1993" depth="6">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="6.25" />
      <Attribute name="realFontWeight" value="400" />
      <Attribute name="realTextColor" value="#999999" />
    </Attributes>
    <Text>DPA</Text>
  </Block>
  <Block left="24" top="1797" right="541" bottom="1809" depth="4">
    <Attributes>
      <Attribute name="realBackgroundColor" value="#ffffff" />
      <Attribute name="realFontSize" value="6.25" />
      <Attribute name="realFontWeight" value="700" />
      <Attribute name="realTextColor" value="#000000" />
    </Attributes>
    <Text>FUSSBALLQUIZ</Text>
  </Block>
  <Block left="220" top="1817" right="512" bottom="1840" depth="5">
    <Attributes>